name: native_admob_flutter
description: Create native ads easily purely in dart using PlatformViews and Google's ADMOB Sdk
version: 0.6.0
repository: https://github.com/bdlukaa/native_admob_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.bruno.native_admob_flutter
        pluginClass: NativeAdmobFlutterPlugin
      ios:
        pluginClass: NativeAdmobFlutterPlugin
